version: '3.7'

services:
  nginx:
    image: nginx:latest
    volumes:
        - ./docker/nginx:/etc/nginx/conf.d
        - ./public:/var/www/html/public
    ports:
        - 8088:80
        - 8080:8080
    depends_on:
        - app
    networks:
        - lesson_net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html:cached
    networks:
      - lesson_net

  masterdb:
    image: mysql:8.0
    volumes:
      - ./docker/masterdb/conf/master.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=lesson
    networks:
      - lesson_net

networks:
  lesson_net:
    driver: bridge
