version: '3.7'

services:
  nginx:
    image: nginx:latest
    volumes:
        - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        - ./public:/var/www/html/public
    ports:
        - 8088:80
        - 8080:8080
    depends_on:
        - app
    networks:
        - lesson_net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html:cached
    networks:
      - lesson_net

networks:
  lesson_net:
    driver: bridge
