name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:8.0
        env:
          MYSQL_USERNAME: root
          MYSQL_ROOT_PASSWORD: pass
          DB_DATABASE: laravel

    steps:
      - uses: actions/checkout@v1
      - uses: nanasess/setup-php@master
        with:
          php-version: '8.0'
      - name: Copy Envfile
        run: |
          cp .env.example .env &
      - name: Composer install
        run: |
          composer install
      - name: Key Generate
        run: |
          php artisan key:generate &
      - name: pcov install
        run: |
          sudo pecl install pcov xdebug
      - name: db migrate
        run: |
          php artisan migrate
      # - name: Run Test
      #   run: php -d pcov.enabled=1 ./vendor/bin/phpunit --coverage-html ~/reports/coverage tests/
